services:
  futebol_web:
    build: .
    container_name: futebol_web
    restart: always
    expose:
      - "8000"
    depends_on:
      - redis

  futebol_celery:
    build: .
    container_name: futebol_celery
    command: celery -A futebol worker --loglevel=info
    depends_on:
      - redis

  futebol_celery_beat:
    build: .
    container_name: futebol_celery_beat
    command: celery -A futebol beat --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: futebol_redis
    ports:
      - "6380:6379"

  nginx:
    image: nginx:latest
    container_name: futebol_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - futebol_web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
