services:
  futebol_web:
    build: .
    container_name: futebol_web
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - futebol_net
    environment:
      - DJANGO_SETTINGS_MODULE=futebol.settings
    volumes:
      - static_volume:/app/staticfiles

  futebol_celery:
    build: .
    container_name: futebol_celery
    command: celery -A futebol worker --loglevel=info
    depends_on:
      - redis
    networks:
      - futebol_net

  futebol_celery_beat:
    build: .
    container_name: futebol_celery_beat
    command: celery -A futebol beat --loglevel=info
    depends_on:
      - redis
    networks:
      - futebol_net

  redis:
    image: redis:7
    container_name: futebol_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - futebol_net

  nginx:
    image: nginx:latest
    container_name: futebol_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - futebol_web
    networks:
      - futebol_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles

networks:
  futebol_net:

volumes:
  redis_data:
  static_volume:
