services:
  futebol_web:
    build: .
    container_name: futebol_web
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - futebol_net
    environment:
      - DJANGO_SETTINGS_MODULE=futebol.settings
    volumes:
      - static_volume:/app/staticfiles

  futebol_celery:
    build: .
    container_name: futebol_celery
    command: celery -A futebol worker --loglevel=info --queues=default --concurrency=4
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - C_FORCE_ROOT=true
    networks:
      - futebol_net

  futebol_celery_beat:
    build: .
    container_name: futebol_celery_beat
    command: celery -A futebol beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - futebol_net

  redis:
    image: redis:7
    container_name: futebol_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - futebol_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: futebol_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - futebol_web
    networks:
      - futebol_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles


networks:
  futebol_net:

volumes:
  redis_data:
  static_volume:
